# Generated by Django 4.2.8 on 2024-01-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilemodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatesettings',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templatesettings',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
