# Generated by Django 4.2.8 on 2024-01-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilemodule', '0002_alter_templatesettings_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='full_cv',
            field=models.FileField(blank=True, null=True, upload_to='cv'),
        ),
        migrations.AlterField(
            model_name='about',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='present_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_background',
            field=models.ImageField(blank=True, null=True, upload_to='others'),
        ),
        migrations.AlterField(
            model_name='about',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
